### ISSUE TITLE
model0.meta does not exist

### ISSUE THREAD

**Issue by colsen-bu** [jaswindersingh2/SPOT-RNA#15]
Hi there! I was having an issue trying to run the program where the SPOT-RNA.py file was running into issues for me on line 64. The readout was as follows:
`Predicting for SPOT-RNA model 0
Traceback (most recent call last):
  File "SPOT-RNA.py", line 64, in <module>
    saver = tf.compat.v1.train.import_meta_graph(os.path.join(base_path, 'SPOT-RNA-models', 'model' + str(MODEL) + '.meta'))
  File "/opt/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1449, in import_meta_graph
    **kwargs)[0]
  File "/opt/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1463, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/opt/anaconda3/envs/venv/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 684, in read_meta_graph_file
    raise IOError("File %s does not exist." % filename)
OSError: File /Users/johnsmith/Desktop/SPOT-RNA/SPOT-RNA-models/model0.meta does not exist.`

I'm not sure how exactly to address this and any advice would be appreciated, the program looks amazing and I would love to figure out how to be able to use it, thanks!

**Comment by jaswindersingh2** [comment]
Hi,

Can you please check whether SPOT-RNA models checkpoints are downloaded correctly?
If you do `ls SPOT-RNA-models/` from SPOT-RNA directory, it should show models checkpoints as below:
![demo](https://user-images.githubusercontent.com/35057243/111949744-fdee3200-8b2c-11eb-9c45-c4219d29731a.PNG)

Please let me know, if checkpoints exists and it is still not working.

Jaswinder

**Comment by colsen-bu** [comment]
Thank you so much for such a speedy reply! I failed to download a file and did not notice, now it is working great, thanks!
